In [1]:
import pandas as pd
import numpy as np
import os
import csv

# Load data

In [2]:
input_dir = "/mnt/c/users/helen/Desktop/test"

In [ ]:
dfs = []

for root, dirs, files in os.walk(input_dir):
    for filename in files:
        if filename.lower().endswith(".csv"):

            path = os.path.join(root, filename)

            df = pd.read_csv(path)

            # Optional metadata
            df["Folder"] = os.path.basename(root)
            df["File"] = filename
            df["Path"] = path

            dfs.append(df)

# Combine all tables
data = pd.concat(dfs, ignore_index=True)

# Create ROI column
data['ROI'] = data['Label'].apply(lambda x: x.split(":")[1])

# Delete first 2 columns
data.drop(data.columns[[0, 1]], axis=1, inplace=True)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [19]:
data

,,Label,Angle,Length,Measurement_type,Folder,File,Path,ROI
0,1,siORC1_MGS1-14_merged.png:0551-0531,41.934,158.619,Fiber_length,siORC1_MGS1-14,siORC1_MGS1-14_Fiber length.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0551-0531
1,2,siORC1_MGS1-14_merged.png:0387-0637,65.283,138.708,Fiber_length,siORC1_MGS1-14,siORC1_MGS1-14_Fiber length.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0387-0637
2,1,siORC1_MGS1-14_merged.png:0533-0514,-44.665,241.835,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0533-0514
3,2,siORC1_MGS1-14_merged.png:0465-0602,-50.928,260.192,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0465-0602
4,3,siORC1_MGS1-14_merged.png:0668-0448,-9.926,162.432,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0668-0448
5,4,siORC1_MGS1-14_merged.png:0752-0491,29.384,236.415,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0752-0491
6,5,siORC1_MGS1-14_merged.png:0732-0894,52.352,176.816,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0732-0894
7,1,siORC1_MGS1-15_merged.png:0619-0711,29.932,228.473,Interorigin_distance,siORC1_MGS1-15,siORC1_MGS1-15_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-15...,0619-0711

In [17]:
data

,Label,Angle,Length,Measurement_type,Folder,File,Path,ROI
0,siORC1_MGS1-14_merged.png:0551-0531,41.934,158.619,Fiber_length,siORC1_MGS1-14,siORC1_MGS1-14_Fiber length.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0551-0531
1,siORC1_MGS1-14_merged.png:0387-0637,65.283,138.708,Fiber_length,siORC1_MGS1-14,siORC1_MGS1-14_Fiber length.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0387-0637
2,siORC1_MGS1-14_merged.png:0533-0514,-44.665,241.835,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0533-0514
3,siORC1_MGS1-14_merged.png:0465-0602,-50.928,260.192,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0465-0602
4,siORC1_MGS1-14_merged.png:0668-0448,-9.926,162.432,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0668-0448
5,siORC1_MGS1-14_merged.png:0752-0491,29.384,236.415,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0752-0491
6,siORC1_MGS1-14_merged.png:0732-0894,52.352,176.816,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...,0732-0894
7,siORC1_MGS1-15_merged.png:0619-0711,29.932,228.473,Interorigin_distance,siORC1_MGS1-15,siORC1_MGS1-15_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-15...,0619-0711

In [ ]:
# Split data into 2 dataframes
fiber_length = data[data['Measurement_type']=='Fiber_length']
iod = data[data['Measurement_type']=='Interorigin_distance']

In [11]:
iod

,,Label,Angle,Length,Measurement_type,Folder,File,Path
2,1,siORC1_MGS1-14_merged.png:0533-0514,-44.665,241.835,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
3,2,siORC1_MGS1-14_merged.png:0465-0602,-50.928,260.192,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
4,3,siORC1_MGS1-14_merged.png:0668-0448,-9.926,162.432,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
5,4,siORC1_MGS1-14_merged.png:0752-0491,29.384,236.415,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
6,5,siORC1_MGS1-14_merged.png:0732-0894,52.352,176.816,Interorigin_distance,siORC1_MGS1-14,siORC1_MGS1-14_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
7,1,siORC1_MGS1-15_merged.png:0619-0711,29.932,228.473,Interorigin_distance,siORC1_MGS1-15,siORC1_MGS1-15_Interorigin distance.csv,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-15...