In [1]:
import pandas as pd
import numpy as np
import os
import csv

# Load data

In [2]:
input_dir = "/mnt/c/users/helen/Desktop/test"

In [ ]:
dfs = []

for root, dirs, files in os.walk(input_dir):
    for filename in files:
        if filename.lower().endswith(".csv"):

            path = os.path.join(root, filename)

            df = pd.read_csv(path)

            # Optional metadata
            df["File"] = os.path.splitext(filename)[0].replace(" ", "_")
            df["Path"] = path

            dfs.append(df) 

# Combine all tables
data = pd.concat(dfs, ignore_index=True)

# Create ROI column
data['ROI'] = data['Label'].apply(lambda x: x.split(":")[1])

# Delete first 3 columns
data.drop(data.columns[[0, 1, 2]], axis=1, inplace=True)

# Reorder columns
data = data[
    [
        "File",
        "Measurement_type",
        "Length",
        "ROI",
        "Path"
    ]
]

# Split data into 2 dataframes
fiber_length = data[data['Measurement_type']=='Fiber_length']
iod = data[data['Measurement_type']=='Interorigin_distance']

AttributeError: 'str' object has no attribute 'replcace'

In [41]:
set(fiber_length['File'])

{'siORC1_MGS1-14_Fiber length'}

In [36]:
conversion_factor = 2.59 # kb/µm
time = 20 # minutes

In [32]:
fiber_length

,File,Measurement_type,Length,ROI,Path
0,siORC1_MGS1-14_Fiber length,Fiber_length,158.619,0551-0531,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
1,siORC1_MGS1-14_Fiber length,Fiber_length,138.708,0387-0637,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...

In [34]:
iod

,File,Measurement_type,Length,ROI,Path
2,siORC1_MGS1-14_Interorigin distance,Interorigin_distance,241.835,0533-0514,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
3,siORC1_MGS1-14_Interorigin distance,Interorigin_distance,260.192,0465-0602,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
4,siORC1_MGS1-14_Interorigin distance,Interorigin_distance,162.432,0668-0448,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
5,siORC1_MGS1-14_Interorigin distance,Interorigin_distance,236.415,0752-0491,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
6,siORC1_MGS1-14_Interorigin distance,Interorigin_distance,176.816,0732-0894,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-14...
7,siORC1_MGS1-15_Interorigin distance,Interorigin_distance,228.473,0619-0711,/mnt/c/users/helen/Desktop/test/siORC1_MGS1-15...