# DNA Fiber Assay Analysis

**Purpose:** Compare replication speed and inter-origin distance between WT and MGS variants.

**Author:** Elena Lopatukhina
**Date:** 2026-07-15

## Workflow
1. Parameters import
2. Data loading
3. Data propcessing
4. Basic statistics calculation
5. Processing outliers
6. Statistical analysis
7. Tables export
8. Graphs plot

# 1. Parameters

In [1]:
INPUT_DIR = "/mnt/c/users/helen/Desktop/180625"
OUTPUT_DIR = "/mnt/c/users/helen/Desktop/180625/results"

pixel_size = 0.16125 # µm
conversion_factor = 2.59 # kb/µm
time = 20 # minutes

# 2. Import data

## 2.1 Data loading

In [2]:
from utils import load_data, data_subset

data = load_data(dir = INPUT_DIR, pixel_size=pixel_size)

print(f"Total number of measurements for analysis is: {data.shape[0]}")

Total number of measurements for analysis is: 439

In [3]:
data

,Sample_name,File,Measurement_type,Length,ROI,Path
0,None,Apt3_1-02_Fiber_length,Fiber_length,13.845892,0321-0342,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
1,None,Apt3_1-02_Fiber_length,Fiber_length,7.783538,0302-0415,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
2,None,Apt3_1-02_Fiber_length,Fiber_length,19.776022,0920-0217,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
3,None,Apt3_1-02_Fiber_length,Fiber_length,7.025018,0905-0308,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
4,None,Apt3_1-02_Fiber_length,Fiber_length,8.249066,0973-0312,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
...,...,...,...,...,...,...
434,None,NC_2-17_Fiber_length,Fiber_length,5.874499,0337-0193,/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...
435,None,NC_2-17_Fiber_length,Fiber_length,7.919794,0170-0614,/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...
436,None,NC_2-17_Fiber_length,Fiber_length,5.037611,0140-0572,/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...
437,None,NC_2-17_Interorigin_distance,Interorigin_distance,18.334286,0681-0559,/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...
438,None,NC_3-03_Interorigin_distance,Interorigin_distance,47.630186,0736-0364,/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...

In [4]:
data['Sample_name'] = data['File'].apply(lambda x: x.split('_')[0])

### 2.2 Manually fill Sample_name column

In [ ]:
# Create Sample name column empty (custom parsing of filenames)
#data['Sample_name'] = data['File'].apply(lambda x: x.split("_")[1].split("-")[0])

#data["Sample_name"] = data["Sample_name"].apply(
#    lambda x: "WT" if "1h15min" in x else x
#)

#data["Sample_name"] = data["Sample_name"].apply(
#    lambda x: "WT" if "30min" in x else x
#)

#mask = (
#    (data["Sample_name"] == "HaloEmpty") &
#    (data["File"].str.contains("siORC1_HaloEmpty", na=False))
#)
#data.loc[mask, "Sample_name"] = "siORC1"

# Update only rows where Sample_name == "HaloEmpty" and File contains "siSCR_HaloEmpty"
#mask = (
#    (data["Sample_name"] == "HaloEmpty") &
#    (data["File"].str.contains("siSCR_HaloEmpty", na=False))
#)

#data.loc[mask, "Sample_name"] = "siSCR"

# Info about samples
#sample_names = set(data["Sample_name"])
#print(f"The amount of samples is: {len(sample_names)}.")
#print(f"There are: {sample_names}")

### 2.3 Split data into replication speed and IOD dataframe

In [5]:
speed = data_subset(df = data, measurement_type = 'Fiber_length')
print(f"The total amount of fibers measurements is: {speed.shape[0]}")

iod = data_subset(df = data, measurement_type = 'Interorigin_distance')
print(f"The total amount of IOD measurements is: {iod.shape[0]}")

The total amount of fibers measurements is: 324
The total amount of IOD measurements is: 115

### 2.4 Checking the number of measurements for each sample

#### 2.4.1 Replication speed
Divide this number by 2 because these are green and red tracks separately.

In [6]:
speed.groupby('Sample_name')['File'].count()

Sample_name
Apt3    144
NC      180
Name: File, dtype: int64

In [ ]:
# OPTIONAL
# Check analized files
#sample_name = "siSCR"
#speed[speed["Sample_name"] == sample_name]['File'].value_counts()

#### 2.4.2. IOD

In [7]:
iod.groupby('Sample_name')['File'].count()

Sample_name
Apt3    40
NC      75
Name: File, dtype: int64

In [ ]:
# OPTIONAL
# Check analized files
#sample_name = "MGS5"
#iod[iod["Sample_name"] == sample_name]['File'].value_counts()

# 3. Data processing

In [8]:
from utils import speed_processing, iod_processing

replication_speed = speed_processing(df = speed, conversion_factor = conversion_factor, time = time)
iod_kb = iod_processing(df = iod, conversion_factor = conversion_factor)

All files contain an even number of fibers.

In [9]:
replication_speed.head()

,Sample_name,File,Speed_kb_min,ROI,Path
0,Apt3,Apt3_1-02_Fiber_length,2.801011,"[0321-0342, 0302-0415]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
1,Apt3,Apt3_1-02_Fiber_length,3.470735,"[0920-0217, 0905-0308]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
2,Apt3,Apt3_1-02_Fiber_length,2.656028,"[0973-0312, 0968-0381]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
3,Apt3,Apt3_1-05_Fiber_length,3.283988,"[0223-1248, 0212-1332]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
4,Apt3,Apt3_1-06_Fiber_length,1.971228,"[0642-0159, 0665-0112]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...

In [10]:
iod_kb.head()

,Sample_name,File,IOD_kb,ROI,Path
6,Apt3,Apt3_1-04_Interorigin_distance,24.823955,0293-0715,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
7,Apt3,Apt3_1-04_Interorigin_distance,44.938630,0278-0790,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
10,Apt3,Apt3_1-05_Interorigin_distance,89.399066,0216-0870,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
25,Apt3,Apt3_1-06_Interorigin_distance,66.387239,0509-0196,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
26,Apt3,Apt3_1-06_Interorigin_distance,60.423794,0530-0441,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...

# 4. Basic statistics calculation

In [11]:
from utils import description_stats

stats_speed = description_stats(replication_speed, col = "Speed_kb_min")
stats_iod = description_stats(iod_kb, col = "IOD_kb")

In [12]:
stats_speed

             Count      Mean   Median        SD
Sample_name
Apt3            72  1.773270  1.68949  0.546187
NC              90  1.916985  1.83275  0.573115

In [13]:
stats_iod

             Count       Mean     Median         SD
Sample_name
Apt3            40  51.531247  48.518619  20.480869
NC              75  58.862342  57.658198  23.448978

# 5. Processing outliers

In [14]:
from utils import outliers

speed_outliers = outliers(df = replication_speed, col = 'Speed_kb_min')
iod_outliers = outliers(df = iod_kb, col = 'IOD_kb')

In [15]:
speed_outliers

,Sample_name,File,Speed_kb_min,ROI,Path
1,Apt3,Apt3_1-02_Fiber_length,3.470735,"[0920-0217, 0905-0308]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
3,Apt3,Apt3_1-05_Fiber_length,3.283988,"[0223-1248, 0212-1332]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
90,NC,NC_1-13_Fiber_length,3.700498,"[0260-0615, 0339-0681]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...
100,NC,NC_1-16_Fiber_length,3.354172,"[0147-0419, 0227-0462]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...
101,NC,NC_1-16_Fiber_length,3.340160,"[0809-0452, 0879-0511]",/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...

In [16]:
iod_outliers

,Sample_name,File,IOD_kb,ROI,Path
131,Apt3,Apt3_2-03_Interorigin_distance,117.785469,0622-0821,/mnt/c/users/helen/Desktop/180625/ROW_DATA/apt...
213,NC,NC_1-06_Interorigin_distance,115.280897,0254-1090,/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...
223,NC,NC_1-10_Interorigin_distance,134.383218,0776-0858,/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...
438,NC,NC_3-03_Interorigin_distance,123.362182,0736-0364,/mnt/c/users/helen/Desktop/180625/ROW_DATA/nc/...

In [ ]:
#iod_kb_clean = iod_kb.drop(index=iod_outliers.index)

# 6. Statistical analysis
Mann-Whetney test (U-test)

In [17]:
from utils import u_test

u_speed = u_test(df = replication_speed, col = "Speed_kb_min", control_sample = "NC")
u_iod = u_test(df = iod_kb, col = "IOD_kb", control_sample = "NC")

In [18]:
u_speed

  Group_1 Group_2  Group_1_n  Group_2_n       U   p-value
0      NC    Apt3         90         72  3794.0  0.062092

In [19]:
u_iod

  Group_1 Group_2  Group_1_n  Group_2_n       U   p-value
0      NC    Apt3         75         40  1786.0  0.093637

# 7. Tables export

In [ ]:
from utils import table_export


# Export of tables with processed results
table_export(df = replication_speed, dir = OUTPUT_DIR, filename = "replication_speed.xlsx")
table_export(df = iod_kb, dir = OUTPUT_DIR, filename = "iod_kb.xlsx")

# Export of tables with descriptive statistics
table_export(df = stats_speed, dir = OUTPUT_DIR, filename = "replication_speed_description.xlsx")
table_export(df = stats_iod, dir = OUTPUT_DIR, filename = "iod_description.xlsx")

# Export of tables with U-test analysis
table_export(df = u_speed, dir = OUTPUT_DIR, filename = "u_speed.xlsx")
table_export(df = u_iod, dir = OUTPUT_DIR, filename = "u_iod.xlsx")

# 8. Graphs with statistics

In [ ]:
from plotting import boxplot_with_statistics

In [ ]:
boxplot_with_statistics(
        data = iod_kb,
        var = "IOD_kb",
        sample_order = ['NC', 'Apt3'],
        sample_labels = {"NC": "NC", "Apt3": "Apt3"},
        sample_colors = {"NC": "#9a9a9a", "Apt3": "#252d8f"},
        sample_markers = {"NC": "o", "Apt3": "^"},
        figsize = (4.5, 5.5),
        stats = [
        {
                "group1": "NC",
                "group2": "Apt3",
                "p_value": 0.04,
        }],
        y_axis = "Inter-Origin Distance (kb)",
        save_dir = OUTPUT_DIR,
        save_name = "IOD_kb",
        ext = "png"
)